### ISSUE TITLE
SAML decommission tracking

### ISSUE THREAD

**Issue by vid** [gctools-outilsgc/gcpedia#269]
- [ ] Banner – initial (12 weeks before implementation till it get replaced by Banner - reminder)
- [ ] Homepage announcement (12 weeks before implementation till it gets removed on implementation day)
- [ ] Login Page (12 weeks before implementation till it gets replaced by Login – post decommission
- [ ] GCpedia Help: Simplified Sign-On Page (12 weeks before implementation. Update after implementation date)

- [ ] Banner – reminder (2 weeks before implementation)
- [ ] Banner – Post decommission (Implementation day and stays one month after)

- [ ] Login Page – post decommission (Implementation day and stays one month after)
